### ISSUE TITLE
USER STORY: Make a Booking

### ISSUE THREAD

**Issue by ZASamm** [surfdemon/theater-booking-system#2]
User Story: As a user, I want to make a booking

Acceptance Criteria:

 User must be logged in to make booking
 User can select number of guests
 System prevents booking if capacity exceeded
 User receives booking confirmation message
 Booking appears in user's booking list
 Event capacity updates after successful booking
 Total price calculated based on guests

**Comment by surfdemon** [comment]
- [x] User must be logged in to make booking
- [x] User can select number of guests
- [x] System prevents booking if capacity exceeded
- [x] User receives booking confirmation message
- [x] Booking appears in user's booking list - It shows in the admin panel as registered to the use that is logged in so should appear on their booking list when the booking list is made.
- [x] Event capacity updates after successful booking
- [x] Total price calculated based on guests
